// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"database/sql"
)

type CardPayment struct {
	GoenID            int32
	CardAccountNumber sql.NullString
	ExpiryDate        sql.NullTime
	GoenPaymentID     sql.NullInt32
}

type CashDesk struct {
	ID       int32
	Name     sql.NullString
	IsOpened sql.NullBool
	StoreID  sql.NullInt32
}

type CashPayment struct {
	GoenID        int32
	Balance       sql.NullFloat64
	GoenPaymentID sql.NullInt32
}

type Cashier struct {
	ID      int32
	Name    sql.NullString
	StoreID sql.NullInt32
}

type Item struct {
	Barcode          int32
	Name             sql.NullString
	Price            sql.NullFloat64
	StockNumber      sql.NullInt32
	OrderPrice       sql.NullFloat64
	StoreID          sql.NullInt32
	ProductCatalogID sql.NullInt32
}

type OrderEntry struct {
	GoenID         int32
	Quantity       sql.NullInt32
	SubAmount      sql.NullFloat64
	ItemID         sql.NullInt32
	OrderProductID sql.NullInt32
}

type OrderProduct struct {
	ID          int32
	Time        sql.NullTime
	OrderStatus sql.NullInt32
	Amount      sql.NullFloat64
	SupplierID  sql.NullInt32
}

type Payment struct {
	GoenType       int32
	GoenID         int32
	AmountTendered sql.NullFloat64
}

type ProductCatalog struct {
	ID      int32
	Name    sql.NullString
	StoreID sql.NullInt32
}

type Sale struct {
	GoenID       int32
	Time         sql.NullTime
	IsComplete   sql.NullBool
	Amount       sql.NullFloat64
	IsReadytoPay sql.NullBool
	PaymentID    sql.NullInt32
	StoreID      sql.NullInt32
	CashDeskID   sql.NullInt32
}

type SalesLineItem struct {
	GoenID    int32
	Quantity  sql.NullInt32
	Subamount sql.NullFloat64
	ItemID    sql.NullInt32
	SaleID    sql.NullInt32
}

type Store struct {
	ID       int32
	Name     sql.NullString
	Address  sql.NullString
	IsOpened sql.NullBool
}

type Supplier struct {
	ID   int32
	Name sql.NullString
}
